### ISSUE TITLE
An example of a task request [Follow this example]

### ISSUE THREAD

**Issue by pet3r-pan** [monero-ecosystem/outreach-docs#1]
**Description of the task to be completed:**
_ eg. Write review the octopus recipe app that only accepts xmr

**What is the goal / reason for completing this task?**
_ eg. To share the appreciation of octopus and xmr

**Comment by erciccione** [comment]
Wha is the task this issue is referring to? @pet3r-pan 
@lh1008 nay clue to leave this issue open?

**Comment by pet3r-pan** [comment]
^^ @erciccione This wasn't referenced to any issue. Just more of a template example.

**Comment by erciccione** [comment]
@pet3r-pan i don't understand which are the tasks this template is referring to

**Comment by pet3r-pan** [comment]
@erciccione this repo was supposed to facilitate the ticketing of tasks. There just aren't any others.

**Comment by lh1008** [comment]
Closing this issue. With the workflow we are having we have not found it useful. Thanks anyway.
