### ISSUE TITLE
Call for translators to update Quick-Facts sheet revised 2/1/2019

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/outreach-docs#100]
Hi everyone,

We just updated some text to the original Quick-facts and are looking to add some minor changes. PR #99 has the text that was changed to the original `en` Quick-Facts Sheet. The languages that we are currently looking to update translation are the following:

- [x] Spanish (es)

- [x] French (fr)

- [ ] Italian (it)

- [x] Portugues (Br)

- [ ] Romanian (ro)

- [x] Russian (ru)

- [ ] Simpiflied Chinese (zh-hans)

- [x] Tradictional Chinese (zh-hant)

- [x] Dutch (nl)

Pinnging contributors 
@xjmzx @BlackLotus64 @Lafudoci @XMRNoblesse @hrumag @el00ruobuob @botoserelepe @netrik182 @Josketobben @v1docq47

**Comment by BlackLotus64** [comment]
Confirming my support with ES language.

**Comment by lh1008** [comment]
Guys a reminder, we are only working the .md files, no longer the .sla files are being edited. The 'en' contains the .sla files if anyone wants to download them and work them in their personal use, but you don't have to work them for submitting your translations.

:)

**Comment by el00ruobuob** [comment]
I will take care of fr soon.

**Comment by Lafudoci** [comment]
I was not aware of this, I'll do zh-hant later.

**Comment by lh1008** [comment]
Hey guys, I had to fix the revised date from the Quick-facts update. I had forgotten to change from 2018 to 2019. Thanks to @v1docq47 who noticed it. Thanks :).

**Comment by Lafudoci** [comment]
@lh1008 PR #101 was pushed.
But I'd like to discuss the date format. M/D/Y was used in the en version, but it's basicall never used in my language. It'll confuse reader. Most of the time we use Y/M/D, some few imported stuff use D/M/Y. So shuold I change it to our manner like Y/M/D while translating?

**Comment by el00ruobuob** [comment]
@Lafudoci, i always used D/M/Y for french, so i believe you could safely use Y/M/D.

**Comment by erciccione** [comment]
For the localized documents, it's better to use the best date format related to that language. Different is for our software, where we have to use the format used for every language

**Comment by v1docq47** [comment]
@lh1008 Russian revised #103 ;)

**Comment by lh1008** [comment]
Hey guys, I have been outside of the scope of the repository because of the scheduled hard fork happening today. So everyone will have the time to update.

:)

**Comment by botoserelepe** [comment]
I'll do the pt-br :)

**Comment by lh1008** [comment]
We are still missing some language updates for the quick-facts:

- [ ] Italian (it)

- [ ] Romanian (ro)

- [ ] Simplified Chinese (zh-hans)

If anyone knows anyone who could help us out, please ping them to this Issue. Will go to the search for more volunteers :).

**Comment by lh1008** [comment]
Closing this issue. We are about to update the quick-facts sheet. If anyone wants to add or continue to update in a new language please go ahead, versions will be saved in every language with their respective versions. Thanks to everyone who contributed. :) :+1:
