### ISSUE TITLE
Typo in english original

### ISSUE THREAD

**Issue by normoes** [monero-ecosystem/outreach-docs#11]
On the very first page of the english original `.sla` file, it says:

> Monero is secure, private, untraceable digital currency that is available for all.

There is a **a** missing. It should say:

> Monero is **a** secure, private, untraceable digital currency that is available for all.

**Comment by lh1008** [comment]
Great catch! Would you like to PR the typo fix?

**Comment by normoes** [comment]
Yes :) Will follow soon.

**Comment by erciccione** [comment]
Resolved by #20
