### ISSUE TITLE
Refuge and Wallet Quickstart Storyboards searching for translators

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/outreach-docs#124]
Hi everyone, 

Anyone interested in making the translation please let us know with a comment, so we can add your username beside of the `article_name`.

*Files are located in **Pull Request #123** or directly in /storyboard folder:
- https://github.com/monero-ecosystem/outreach-docs/blob/master/monero-outreach-docs/en/storyboard/refuge_en.md
- https://github.com/monero-ecosystem/outreach-docs/blob/master/monero-outreach-docs/en/storyboard/wallet_quickstart_en.md

- [x] Spanish (es)
Assign too:
+ `Refuge:` @lh1008 - PR: #129 MERGED
+ `Wallet_quickstart:` @BlackLotus64 - PR: #131 MERGED

- [x] French (fr)
Assign too:
+ `Refuge:` @el00ruobuob - PR #136 MERGED
+ `Wallet_quickstart:` @el00ruobuob - PR #151 MERGED

- [x] Brazilian Portuguese (pt-br)
Assign too:
+ `Refuge:` @botoserelepe - PR: #133 MERGED
+ `Wallet_quickstart:` @botoserelepe - PR #137 MERGED

- [ ] Chinese Traditional (zh-hant)
Assign too:
+ `Refuge:`
+ `Wallet_quickstart:` @Lafudoci 

- [x] Chinese Simplified (zh-hans)
Assign too:
+ `Refuge:` @XMRNoblesse - PR #144 MERGED
+ `Wallet_quickstart:` @al-mutasim - PR: #132 MERGED

- [ ] Italian (it)
Assign too:
+ `Refuge:`
+ `Wallet_quickstart:`

- [x] Russian (ru)
Assign too:
+ `Refuge:` @v1docq47 - PR: #127 MERGED
+ `Wallet_quickstart:` @v1docq47 - PR: #127 MERGED

- [ ] Dutch (nl)
Assign too:
+ `Refuge:` @Josketobben - PR: #128 
+ `Wallet_quickstart:` @Josketobben - PR: #128

@erciccione not pinging anyone yet. Once merged will ping contributors. 

*If anyone wants to work a new language we can add the language, just leave a comment.*

**Comment by lh1008** [comment]
Pinging contributors to this issue:
@Lafudoci @almutsim @xjmzx @el00ruobuob @hrumag @botoserelepe @netrik182 @rating89us @ProkhorZ @v1docq47 @BlackLotus64 @XMRNoblesse @Josketobben @Gmv1337 @rmbb @Viking0x @krista89

If I missed any @erciccione or you can add more please do :).

**Comment by Lafudoci** [comment]
I'll find some time to do zh-hant for `Wallet_quickstart`

**Comment by Josketobben** [comment]
Sure, I'll do the Dutch.

**Comment by botoserelepe** [comment]
Hey @lh1008 
I'll do the "Refuge" translation to pt-br.

**Comment by BlackLotus64** [comment]
Hello @lh1008, I'm up to the translation of Wallet_quickstart :)

**Comment by v1docq47** [comment]
Hi @lh1008!
Russian translate "Refuge and Wallet Quickstart" done #127

**Comment by Josketobben** [comment]
Just did the PR for Refuge_nl
(Wallet_quickstart is still open if there are any other Dutchies reading!)

**Comment by lh1008** [comment]
@Josketobben are you also going to work out the wallet_nl?

**Comment by XMRNoblesse** [comment]
Chinese refuge.

**Comment by Josketobben** [comment]
@lh1008 Nobody else is biting, so yeah I'll take wallet_nl as well.

**Comment by lh1008** [comment]
Thanks @Josketobben take a look at the last comment made by @erciccione in the PR #128, you added the file in the same PR of the refuge article, change the title of the PR by adding the wallet article also. I will be checking the file soon :). Great work, thanks.

**Comment by erciccione** [comment]
@lh1008 Just a side note. IMO would be better to open single issues in the future and i suggest to do it in the future. It would make easier to keep track of the issues, since they can be closed once a language is finished, i'm afraid having a single issue for all languages might not give a clear idea of what is needed to a potential contributors. Also, now GitHub allows to assign task also to contributors who are not maintainers, that makes even easier to see who is working on an issue.

**Comment by Lafudoci** [comment]
@lh1008 Sorry it took a while, PR #160 was pushed.
