### ISSUE TITLE
Is it really necessary to have a printer friendly version of the documents?

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/outreach-docs#13]
Having two documents make translations harder to manage and, in general, i would avoid a double version of the same file. I suggest to only have a single version of each document, maybe the printer friendly one.
@lh1008 @xmrhaelan opinions?

**Comment by lh1008** [comment]
Hi @erciccione,

I spoke with our design leader he told me "that managing both versions is more difficult, but I also think visual impact matters", so basically the two versions are a way of giving more to the Monero Project. We have had already contributors that didn't find any trouble working both files. What we had to do, were design reviews and then submit those changes to the contributors so they can add them to the PR. 
Our lead designer also told me this issue will be solved with technology. He has an idea in mind on how to fix this out and make it much easier to work, but that will be something for the near future. So by now, we should try to work with what we have. What do you think? :)

**Comment by erciccione** [comment]
>  We have had already contributors that didn't find any trouble working both files.

This is true when the files to work on are just one single document translated in a handful of languages. when the files will be many and each one of them will have more than one version, my feeling is that reviews and edits will be much more complicated

> Our lead designer also told me this issue will be solved with technology. He has an idea in mind on how to fix this out and make it much easier to work, but that will be something for the near future. So by now, we should try to work with what we have. What do you think? :)

Good for me. Closing this issue
