### ISSUE TITLE
Missed getmonero.org/ru links in #135

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/outreach-docs#139]
Hey everyone,

Noticed we missed the getmonero.org/ru links #135.

Made my comment here:
https://github.com/monero-ecosystem/outreach-docs/pull/135#pullrequestreview-245790116

Pinging @v1docq47, @monerorus, @LvMsterfild, @TheFuzzStone

Thank you everyone >:)

**Comment by v1docq47** [comment]
Thanks @lh1008!
I'll do it soon ;)

**Comment by lh1008** [comment]
Awesome, thank you @v1docq47 >:)

**Comment by v1docq47** [comment]
Hi@lh1008 ;)
I fix links in #142

**Comment by lh1008** [comment]
Thank you @v1docq47, really fast. Will close the issue then #142 is merged. 

>:)

**Comment by erciccione** [comment]
#142 is merged
