### ISSUE TITLE
[Test] Testing integration bot on #monero-translations

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/outreach-docs#146]
Testing the new notification bot

**Comment by erciccione** [comment]
The bot is working. From now on when an issue or pull request is open on this repo, the channel `#monero-translations` will get a notification. This will help translators idling in that room to be notified when a review/translation is needed.

Ping @lh1008

**Comment by lh1008** [comment]
Yes, I noticed. Amazing.
