### ISSUE TITLE
RandomX - French (fr) Translation

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/outreach-docs#165]
Hey everyone,

**Before adding/submitting any work please read the Outreach Localization EPIC:**
https://taiga.getmonero.org/project/xmrhaelan-monero-public-relations/epic/69

_Searching for french contributors, take a look at the taiga instance:_
https://taiga.getmonero.org/project/xmrhaelan-monero-public-relations/task/164

Any questions?

**Comment by lh1008** [comment]
Assigned to @4593429418533 
Made the translation here:

https://github.com/monero-ecosystem/outreach-docs/commit/f27b719eac59bd46cc047f409b8b5edd1ba2e381#commitcomment-34443970

**Comment by erciccione** [comment]
@4593429418533 please comment here so that i can assign the issue to you.

**Comment by 4593429418533** [comment]
> 
> 
> @4593429418533 please comment here so that i can assign the issue to you.

I'm here

**Comment by erciccione** [comment]
In progress in #169

**Comment by Tomahna81** [comment]
Whenever a review of the translation will be required, let me know and I can tackle it.

**Comment by erciccione** [comment]
This was resolved with #194.
