### ISSUE TITLE
rename file 'konferenco-2019/ASIC-resistant_proof_of_work:_fact_or_fantasy.md'

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/outreach-docs#171]
Apparently the `:` is breaking the format for Windows users (`:` cannot be in a file name)

reported by Mr. Pickles

**Comment by erciccione** [comment]
I'll take care of this later today.

**Comment by lh1008** [comment]
oh ok, I also had same trouble with #161. Until I didn't remove the ":" the file had a strange error when trying submitting the PR.
