### ISSUE TITLE
Link leads to 404

### ISSUE THREAD

**Issue by b068931cc450442b63f5b3d276ea4297** [monero-ecosystem/outreach-docs#287]
In outreach-docs/monero-outreach-docs/translations/README.md the following [Link](https://github.com/monero-ecosystem/outreach-docs/blob/master/monero-outreach-docs/README_i18n.md) leads to 404 error.

**Comment by lh1008** [comment]
I've got this one: https://github.com/monero-ecosystem/outreach-docs/blob/master/monero-outreach-docs/translations/README.md

**Comment by lh1008** [comment]
Oh, okay I get it, let me fix it.
