### ISSUE TITLE
The font 'Adobe Caslon' is copyrighted and should be removed

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/outreach-docs#45]
This to avoid copyright issues. Since a license should be paid to use it. We should find an alternative

@lh1008 @thunderosa @xmrhaelan

**Comment by BlackLotus64** [comment]
There's a great variety of fonts in DaFont, a site I've been using for a while. Also there should be a similar font in the default ones that we can use, if you want to I can play a bit with the design and upload examples or captures of it.

**Comment by erciccione** [comment]
@BlackLotus64 That's something you should ask directly to the outreach workgroup, but according to what i read on the telegram chat, i think they already started to take care of the issue.

**Comment by xmrhaelan** [comment]
Please check with @thunderosa about the fonts. He has spent a considerable amount of time on it.

**Comment by erciccione** [comment]
@xmrhaelan I manage this repo voluntarily with pleasure and i help taking care of the translations, since it's part of my job. But the outreach workgroup has a coordinator and an organizer funded by the community. I think this is something that one of those two figures should take care of.

**Comment by lh1008** [comment]
>This to avoid copyright issues. Since a license should be paid to use it. We should find an alternative

Thanks for the notice @erciccione, I will be removing the adobe fonts and leaving the monero fonts only. We still need to work on this a little more. 

Thank you.

>There's a great variety of fonts in DaFont, a site I've been using for a while. Also there should be a similar font in the default ones that we can use, if you want to I can play a bit with the design and upload examples or captures of it.

@BlackLotus64 I know @thunderosa has been working on the fonts so we have Monero original fonts. You can find them in here: https://www.monerooutreach.org/monero-typography.php. They were added in the  [README_i18](https://github.com/monero-ecosystem/outreach-docs/blob/master/monero-outreach-docs/README_i18n.md), in PR #33.

I will be leaving a comment with the PR addressing those changes soon. 

Thanks guys.

**Comment by lh1008** [comment]
See #46.

**Comment by erciccione** [comment]
This is resolved

**Comment by lh1008** [comment]
Thank you @erciccione
