### ISSUE TITLE
Update descriptions Repository

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/outreach-docs#48]
>Monero's community outreach and education wing https://t.me/joinchat/DM8-zUXYPy2QPEk…

Hi @erciccione,

The telegram link of the repository's description needs to be updated for:  https://t.me/monerooutreach.

Thanks. 

*I don't have permission to change it and not sure how to do a PR suggesting the change.

**Comment by erciccione** [comment]
Link updated. Thanks
