### ISSUE TITLE
Call for translators to update some text in the Quick-Facts sheet

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/outreach-docs#59]
Hi everyone,

We just updated some text to the original Quick-facts and are looking to add some minor changes. PR #49 has the text that was changed to the original `en` Quick-Facts Sheet. The languages that we are currently looking to translate are the following:

- [x] French (fr)

- [x] Russian (ru)

- [x] Italian (it)

- [x] zh-hans (simplified chinese)

- [x] zh-hant (traditional chinese)

- [ ] Romanian (ro)

Thank you all for your contributions.

PR #49 was missing an update. Thanks to @Lafudoci I was able to take notice of it:

- Page 5
_Revised 11/14/2018_

*It has already been added.

**Comment by erciccione** [comment]
@hrumag @el00ruobuob 

@lh1008 could you ping other contributors? so that they will see this issue

**Comment by el00ruobuob** [comment]
I'll be doing this tomorrow.

**Comment by lh1008** [comment]
Sure @erciccione,

@xjmzx @Lafudoci @hrumag @rmbb @v1docq47 

Can you guys help us out on updating the files?

**Comment by Lafudoci** [comment]
Sure, I'll check later.

**Comment by v1docq47** [comment]
Thank you! Soon will do!

**Comment by Lafudoci** [comment]
zh-hant version was updated #61

**Comment by v1docq47** [comment]
russian version was update #14

**Comment by hrumag** [comment]
And here it is... italian version! #67 :)

**Comment by lh1008** [comment]
Closing this issue, thank you to all of the translators support and work. @erciccione thank you too also and I will be searching for Romanian review. :heart:
