### ISSUE TITLE
How should I print the Quick Facts flyer?

### ISSUE THREAD

**Issue by ProkhorZ** [monero-ecosystem/outreach-docs#74]
I want to make flyers for my meetup tomorrow, but how do I make a flyer from 5 pages? Also, the text is very small on A5 format. Should it be printed without any margins?

I'm not going to contact the workgroup on Wire or Telegram, I'm already using IRC, Reddit, Twitter, Github, Gitlab, self-hosted Gitlab, the Monero forum and Bitcointalk. And the Twitter contact is some Ethereum guy???

Update: example of what I tried to print.

![20190110_000745](https://user-images.githubusercontent.com/22837744/50935589-cc697e80-146c-11e9-9335-4418335b22a5.jpg)

![20190110_000753](https://user-images.githubusercontent.com/22837744/50935596-d12e3280-146c-11e9-93a7-be2bd1088898.jpg)

**Comment by xjmzx** [comment]
If the text is too small, you could print double-paged (facing) like you have, but on A3 or A4, and cut that to A4 or A5, to increase the size. Looks fine to me, maybe the text is a bit dense for a flyer?

**Comment by ProkhorZ** [comment]
Thanks for the quick reply! Solution: I'm printing only page 2 and 3 on A4. I don't want to give noobs a stack of paper, and I don't want to give them too much information at once anyway.

**Comment by Thunderosa** [comment]
Each facing page was designed to be 8.5" x 11"

Yes, this was designed to be full bleed which means the margins get cut off when being printed. Small quantities can be cut with an x-acto blade and a ruler easily. For a larger quantity a print shop will usually do it for you. Often pages will be ganged up on a larger sheet of paper and cut from there.
