### ISSUE TITLE
All new added .md files need to be correctly converted to markdown

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/outreach-docs#79]
All files recently converted to markdown were just copy-pasted. The structure of those files is now broken, since the proper markdown formatting wasn't respected.

All files recently converted need to be checked and fixed. At the moment, at least all versions of `QuickFacts_[LANGUAGE].md` are broken.

Also apply for #78 

Need to ve fixed:

- [x] Quickfacts EN (#80)
- [x] Quickfacts RO
- [x] Quickfacts ES
- [x] Quickfacts FR
- [x] Quickfacts IT
- [x] Quickfacts PT-BR
- [x] Quickfacts zh-hans

@BlackLotus64 @lh1008 please fix

**Comment by lh1008** [comment]
Can you give us an example @erciccione so we can see?

I'm not having any trouble with the files.

**Comment by lh1008** [comment]
Oh, I already saw what you mean. We will work that today. Thanks for the notice :).

**Comment by BlackLotus64** [comment]
**zh-hant** and **ru** are still not converted to MD files so they don't "need" a fix.

**Comment by lh1008** [comment]
Looks good to me :).

**Comment by erciccione** [comment]
All are fixed
